### ISSUE TITLE
`NaN` values of `calculate_phi_part` function

### ISSUE THREAD

**Issue by PrzeChoj** [PrzeChoj/gips#5] opened 2022-05-04 21:31 UTC
Sometimes the `calculate_phi_part` tries to return the NaN or Inf value. This is most likely caused by the <img src="https://render.githubusercontent.com/render/math?math=0^{-\varepsilon}"> situation for <img src="https://render.githubusercontent.com/render/math?math=\varepsilon>0">.

Further investigation is needed. It is not known if this is caused by the actual <img src="https://render.githubusercontent.com/render/math?math=0"> showing up or if sth very close to <img src="https://render.githubusercontent.com/render/math?math=0"> that R cannot distinguish from it.

**Comment by PrzeChoj** [comment] 2022-05-10 21:14
Example:
```
library(gips)
library(permutations)
set.seed(1234)

p <- 20
n <- 25
actual_permutation <- as.cycle(as.word(c(2:p, 1)))

draw_U <- function(p, n){
  mu <- numeric(p)
  sigma <- matrix(numeric(p*p), nrow=p)
  for(i in 1:p){
    for(j in 1:p){
      sigma[i,j] <- 1 - min(abs(i-j), p-abs(i-j)) / p
    }
    sigma[i,i] <- 1 + 1/p
  }
  
  Z <- MASS::mvrnorm(n, mu = mu, Sigma = sigma)
  U <- t(Z) %*% Z
  
  U
}

U <- draw_U(p, n)
goal_function(actual_permutation, n, U) # 1.859415e+64

n_inf <- 35
U <- draw_U(p, n_inf)
goal_function(actual_permutation, n_inf, U) # Inf

n_nan <- 250
U <- draw_U(p, n_nan)
goal_function(permutations::id, n_nan, U) # NaN
```

**Comment by MrDomani** [comment] 2022-05-18 08:15
Overall, in MH G_part tends to be really large, while phi_part tends to be really small.
Issues were caused either by G_part being calculated as Inf, or phi_part as 0 (or both - we get nan then).
Partially fixed by delaying product calculation into the goal_function, so that individual product terms of G_part and phi_part have chance to cancel themselves out.
Unfortunately, for permutations with structure constant L=1 (like id) fix does nothing. Issue there is caused by `calculate_gamma_omega` for large (~200-250) `lambda` parameters (returns Inf).

**Comment by MrDomani** [comment] 2022-05-18 11:24
R fails to calculate `base::gamma(250)` - returns Inf. However, there is a function called `lgamma`, which returns logarithm of gamma function - `base::lgamma(250) == 1128.54`. Switching the computation to logarithms could do the trick. Since we are doing a lot of multiplication and almost no addition, it shouldn't be a problem.

**Comment by PrzeChoj** [comment] 2022-05-19 13:13
I think the introduction of logarithmic calculations solved this problem for small p. For more significant p, this is still potentially a problem, but it is easier to run out of RAM on my computer than the place in a float variable.

On my machine, I did not have this problem anymore for <img src="https://render.githubusercontent.com/render/math?math=p<500">. I have left the note in `MH()` that links to this ISSUE if someone has this problem in the future.

**We strongly encourage everyone to reopen this ISSUE in case of a NaN value problem.**

**Comment by MrDomani** [comment] 2022-12-06 12:56
Issue occurred for breast_cancer data (~50 obs, 150 variables) and D matrix with 1000 on diagonal. Later execution was halted because of error in `validate_gips`.

**Comment by PrzeChoj** [comment] 2022-12-24 22:43
I believe this is caused by the infinity here:
```
D_matrix <- diag(150) * 1000 / 2
det(D_matrix)
#> Inf
```

Later in the code, we calculate the difference `log(det(block_matrix1)) - log(det(block_matrix2))`, which are both `Inf` and the term goes `NaN`.

I believe all the time we use the `det` function, it is later sent to the `log` function.
Looking at the implementation of the `det` function:
```
> det
function (x, ...) 
{
    z <- determinant(x, logarithm = TRUE, ...)
    c(z$sign * exp(z$modulus))
}
```
I think we should just use `determinant(x, logarithm = TRUE)`

**Comment by PrzeChoj** [comment] 2022-12-25 01:04
Yep, it worked. 

The code from #31 does not produce a `NaN`. Also, the `breast_cancer` data does not produces `NaN`, for `D_coef <- 1000`. It even works for `D_coef <- 1e300`, but does not work for `D_coef <- 1e350`.

Should be enough for everybody of sound mind.

**Closed as completed** 2023-02-28 11:14 UTC
Labels: bug
